export const allUSACanadaTimeZoneAbbreviationsData = {
  'Pacific/Midway': 'SMST',
  'Pacific/Honolulu': 'HAST',
  'America/Juneau': 'AK',
  'America/Boise': 'MT',
  'America/Dawson': 'YDA',
  'America/Chihuahua': 'MSTM',
  'America/Phoenix': 'MST',
  'America/Chicago': 'CT',
  'America/Regina': 'CCST',
  'America/Mexico_City': 'CSTM',
  'America/Belize': 'CAST',
  'America/Detroit': 'ET',
  'America/Bogota': 'SAPST',
  'America/Caracas': 'VST',
  'America/Santiago': 'PSAST',
  'America/St_Johns': 'NDT',
  'America/Sao_Paulo': 'ESAST',
  'America/Tijuana': 'PSTM',
  'America/Montevideo': 'MVD',
  'America/Argentina/Buenos_Aires': 'ART',
  'America/Godthab': 'GNST',
  'America/Los_Angeles': 'PT',
  'Atlantic/Azores': 'AZOST',
  'Atlantic/Cape_Verde': 'TCV',
};
